services:
  backend:
    build:
      context: .
      dockerfile: ./assignment/Dockerfile
    container_name: backend1
    ports: 
     - "8000:8000"
    environment:
      # Database
      DATABASE_URL: mongodb://admin:password@mongodb:27017/?authSource=admin
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: admin
      MONGO_PASSWORD: password
      MONGO_DB: mydb
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 1
      PYTHONUNBUFFERED: 1
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - practice
    restart: unless-stopped
  
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongodb_data:/data/db
    networks:
      - practice
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - practice
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  worker:
    build:
      context: .
      dockerfile: ./assignment/Dockerfile
    container_name: worker
    command: arq assignment.core.worker.WorkerSettings
    environment:
      DATABASE_URL: mongodb://admin:password@mongodb:27017/?authSource=admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 1
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: admin
      MONGO_PASSWORD: password
      MONGO_DB: mydb
      PYTHONUNBUFFERED: 1
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - practice
    restart: unless-stopped
volumes:
  mongodb_data:

networks:
  practice:
    driver: bridge